on:
  push:
    tags:
      - docs@**

name: Deploy

jobs:
  deploy-docs:
    name: Deploy to S3 and CloudFront
    runs-on: ubuntu-latest
    environment: prod

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: reggionick/s3-deploy@v4
        with:
          folder: build
          bucket: ${{ secrets.S3_BUCKET_NAME }}
          bucket-region: us-east-1
          dist-id: ${{ secrets.CLOUDFRONT_DIST_ID }}
          invalidation: /*
          delete-removed: true
          private: true
          files-to-include: '{.*/**,**}'
